version: '3.9'

services:
  backend:
    build: ./backend
    ports:
      - "8080:8080"
    restart: always

  frontend:
    build: ./frontend
    ports:
      - "3000:3000"
    environment:
      - NEXT_PUBLIC_API_URL=http://localhost:8080
    depends_on:
      - backend
    restart: always
